Cs: 0.001
D: 25
L_pore: 50
L_wall: 20
N: 25
S: 50
chi_solv: 0.5
chi_surf: 0
epsilon_surf: 80
max_val: 0.1
min_val: 0.1
output_dir: 2D_pore_in_files_eps
range_param: Cs
space: 15
target_dir: /home/tpopova/prj/PB_SCF/08_2D_pore/scf_templates
valence: -0.5
