Cs: 0.01
D: 10
L_pore: 10
L_wall: 10
N: 10
S: 100
chi_solv: 0.5
chi_surf: -0.55
max_val: 0.5
min_val: 0.5
output_dir: 2D_pore_in_files
range_param: Cs
space: 10
target_dir: /home/tpopova/prj/PB_SCF/08_2D_pore/scf_templates
valence: -0.5
