Cs: 0.001
D: 30
L_pore: 50
L_wall: 10
N: 20
S: 100
chi_solv: 0.5
chi_surf: -0.55
max_val: 0.1
min_val: 0.1
output_dir: 2D_pore_in_files_fig4
range_param: Cs
space: 8
target_dir: /home/tpopova/prj/PB_SCF/08_2D_pore/scf_templates
valence: -0.5
