Cs: 0.005
D: 20
L_pore: 40
L_wall: 30
N: 20
S: 100
chi_solv: 0.5
chi_surf: 0
epsilon_surf: 90
max_val: 0.1
min_val: 0.1
output_dir: 2D_pore_in_files_eps
range_param: Cs
space: 10
target_dir: /home/tpopova/prj/PB_SCF/08_2D_pore/scf_templates
valence: -0.5
