Cs: 0.005
D: 50
L_pore: 130
L_wall: 30
N: 50
S: 50
chi_solv: 0.5
chi_surf: 0
max_val: 0.1
min_val: 0.1
output_dir: 2D_pore_in_files_fig2
range_param: Cs
space: 10
target_dir: /home/tpopova/prj/PB_SCF/08_2D_pore/scf_templates
valence: -0.5
